//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALARm {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class alerts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal alerts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALARm.alerts", typeof(alerts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дистанция.
        /// </summary>
        public static string adm_distance {
            get {
                return ResourceManager.GetString("adm_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорога.
        /// </summary>
        public static string adm_road {
            get {
                return ResourceManager.GetString("adm_road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, для начала заполните родительскую таблицу.
        /// </summary>
        public static string before_insert {
            get {
                return ResourceManager.GetString("before_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, для начала ввода заполните таблицу периодов действия.
        /// </summary>
        public static string before_insert_period {
            get {
                return ResourceManager.GetString("before_insert_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, для начала заполните таблицу путей.
        /// </summary>
        public static string before_insert_track {
            get {
                return ResourceManager.GetString("before_insert_track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, проверьте корректность вводимых данных .
        /// </summary>
        public static string check_fields_filling {
            get {
                return ResourceManager.GetString("check_fields_filling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руководитель.
        /// </summary>
        public static string chief_full_name {
            get {
                return ResourceManager.GetString("chief_full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Класс.
        /// </summary>
        public static string class_ {
            get {
                return ResourceManager.GetString("class_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вводимые данные пересекаются с имеющимися.
        /// </summary>
        public static string coord_overlaps {
            get {
                return ResourceManager.GetString("coord_overlaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала действия должна быть меньше даты окончания действия.
        /// </summary>
        public static string date_overlaps {
            get {
                return ResourceManager.GetString("date_overlaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление....
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось изменить запись.
        /// </summary>
        public static string edit_error {
            get {
                return ResourceManager.GetString("edit_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение.
        /// </summary>
        public static string editing {
            get {
                return ResourceManager.GetString("editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица пустая.
        /// </summary>
        public static string empty_table {
            get {
                return ResourceManager.GetString("empty_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сделать экспорт.
        /// </summary>
        public static string export_error {
            get {
                return ResourceManager.GetString("export_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, заполните все поля.
        /// </summary>
        public static string filling_error {
            get {
                return ResourceManager.GetString("filling_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конец (км).
        /// </summary>
        public static string final_km {
            get {
                return ResourceManager.GetString("final_km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конец (м).
        /// </summary>
        public static string final_m {
            get {
                return ResourceManager.GetString("final_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участок дистанции.
        /// </summary>
        public static string frm_distance_caption {
            get {
                return ResourceManager.GetString("frm_distance_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось генерировать путевой лист.
        /// </summary>
        public static string generate_list_error {
            get {
                return ResourceManager.GetString("generate_list_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сделать импорт.
        /// </summary>
        public static string import_error {
            get {
                return ResourceManager.GetString("import_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось добавить запись .
        /// </summary>
        public static string insert_error {
            get {
                return ResourceManager.GetString("insert_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление записи.
        /// </summary>
        public static string inserting {
            get {
                return ResourceManager.GetString("inserting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Километр.
        /// </summary>
        public static string km {
            get {
                return ResourceManager.GetString("km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина.
        /// </summary>
        public static string length {
            get {
                return ResourceManager.GetString("length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует направления.
        /// </summary>
        public static string NoDirection {
            get {
                return ResourceManager.GetString("NoDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нестандартные километры.
        /// </summary>
        public static string nonstandard_km {
            get {
                return ResourceManager.GetString("nonstandard_km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует станции.
        /// </summary>
        public static string NoStations {
            get {
                return ResourceManager.GetString("NoStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует главные пути.
        /// </summary>
        public static string NoTracks {
            get {
                return ResourceManager.GetString("NoTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить эту запись?.
        /// </summary>
        public static string remove_ask {
            get {
                return ResourceManager.GetString("remove_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало (км).
        /// </summary>
        public static string start_km {
            get {
                return ResourceManager.GetString("start_km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало (м).
        /// </summary>
        public static string start_m {
            get {
                return ResourceManager.GetString("start_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция выполнена успешно.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
    }
}
