//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALARm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALARm.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=369,Y=245}.
        /// </summary>
        public static System.Drawing.Point artificialConstructionBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("artificialConstructionBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Avg_level_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Avg_level.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Avg_width_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Avg_width.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Axis_Km_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Axis_Km.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Axis_M_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Axis_M.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=399,Y=440}.
        /// </summary>
        public static System.Drawing.Point ballastTypeBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("ballastTypeBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Brace_Type_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Brace_Type.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool chamjoint_type_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("chamjoint_type_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=794,Y=284}.
        /// </summary>
        public static System.Drawing.Point chamJointBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("chamJointBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=362}.
        /// </summary>
        public static System.Drawing.Point checkSectionBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("checkSectionBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Column1_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column1.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Column2_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column2.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=695,Y=401}.
        /// </summary>
        public static System.Drawing.Point communicationBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("communicationBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=910,Y=401}.
        /// </summary>
        public static System.Drawing.Point coordinateGNSSBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("coordinateGNSSBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=659,Y=17}.
        /// </summary>
        public static System.Drawing.Point crossTieBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("crossTieBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=442,Y=206}.
        /// </summary>
        public static System.Drawing.Point curveBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("curveBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn17_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn17.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn18_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn18.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn19_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn19.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn21_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn21.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn28_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn28.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn33_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn33.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn48_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn48.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn53_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn53.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn58_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn58.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn59_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn59.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn91_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn91.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn97_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn97.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=241,Y=440}.
        /// </summary>
        public static System.Drawing.Point deepBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("deepBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=497,Y=401}.
        /// </summary>
        public static System.Drawing.Point defectsEarthBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("defectsEarthBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=703,Y=440}.
        /// </summary>
        public static System.Drawing.Point dimensionBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("dimensionBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Distance_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Distance.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=241,Y=401}.
        /// </summary>
        public static System.Drawing.Point distanceBetweenTracksBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("distanceBetweenTracksBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=362,Y=17}.
        /// </summary>
        public static System.Drawing.Point distSectionBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("distSectionBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=824,Y=362}.
        /// </summary>
        public static System.Drawing.Point elCurveBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("elCurveBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=643,Y=128}.
        /// </summary>
        public static System.Drawing.Point elevationBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("elevationBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Empty_Freight_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Empty_Freight.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Final_Km_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Final_Km.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Final_M_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Final_M.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Freight_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Freight.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Lastochka_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Lastochka.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool longrails_type_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("longrails_type_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=508,Y=167}.
        /// </summary>
        public static System.Drawing.Point longRailsBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("longRailsBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point menuStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Meter_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Meter.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=132,Y=17}.
        /// </summary>
        public static System.Drawing.Point miniToolStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("miniToolStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=203,Y=323}.
        /// </summary>
        public static System.Drawing.Point mtoTrafficBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("mtoTrafficBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=209,Y=167}.
        /// </summary>
        public static System.Drawing.Point nonExistKmBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("nonExistKmBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=164,Y=56}.
        /// </summary>
        public static System.Drawing.Point nonstandardKmBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("nonstandardKmBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=304,Y=95}.
        /// </summary>
        public static System.Drawing.Point normaWidthBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("normaWidthBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Num_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Num.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Pdb_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Pdb.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=167}.
        /// </summary>
        public static System.Drawing.Point pdbSectionBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("pdbSectionBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=128}.
        /// </summary>
        public static System.Drawing.Point profileObjectBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("profileObjectBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=323}.
        /// </summary>
        public static System.Drawing.Point profmarksBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("profmarksBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=95}.
        /// </summary>
        public static System.Drawing.Point railsBraceBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("railsBraceBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool RailsSections_Type_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("RailsSections_Type.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=688,Y=167}.
        /// </summary>
        public static System.Drawing.Point railsSectionsBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("railsSectionsBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Reason_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Reason.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=368,Y=362}.
        /// </summary>
        public static System.Drawing.Point refPointBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("refPointBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=842,Y=323}.
        /// </summary>
        public static System.Drawing.Point repairProjectBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("repairProjectBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=219,Y=362}.
        /// </summary>
        public static System.Drawing.Point rfidBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("rfidBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Sapsan_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Sapsan.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Sko_level_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Sko_level.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Sko_width_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Sko_width.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Speed_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Speed.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=608,Y=95}.
        /// </summary>
        public static System.Drawing.Point speedBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("speedBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Start_Km_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Start_Km.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Start_M_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Start_M.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Station_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Station.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=206}.
        /// </summary>
        public static System.Drawing.Point stationSectionBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("stationSectionBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool StationSwitch_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("StationSwitch.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=653,Y=362}.
        /// </summary>
        public static System.Drawing.Point stCurveBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("stCurveBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=245}.
        /// </summary>
        public static System.Drawing.Point straighteningThreadBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("straighteningThreadBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=724,Y=245}.
        /// </summary>
        public static System.Drawing.Point switchBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("switchBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool switchMeter_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("switchMeter.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=345,Y=128}.
        /// </summary>
        public static System.Drawing.Point tempSpeedBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tempSpeedBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=890,Y=440}.
        /// </summary>
        public static System.Drawing.Point timer1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=284}.
        /// </summary>
        public static System.Drawing.Point toolStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=330,Y=206}.
        /// </summary>
        public static System.Drawing.Point toolStrip10_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip10.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=773,Y=206}.
        /// </summary>
        public static System.Drawing.Point toolStrip11_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip11.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=257,Y=245}.
        /// </summary>
        public static System.Drawing.Point toolStrip12_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip12.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=612,Y=245}.
        /// </summary>
        public static System.Drawing.Point toolStrip13_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip13.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=122,Y=284}.
        /// </summary>
        public static System.Drawing.Point toolStrip14_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip14.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=234,Y=284}.
        /// </summary>
        public static System.Drawing.Point toolStrip15_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip15.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=346,Y=284}.
        /// </summary>
        public static System.Drawing.Point toolStrip16_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip16.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=458,Y=284}.
        /// </summary>
        public static System.Drawing.Point toolStrip17_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip17.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=570,Y=284}.
        /// </summary>
        public static System.Drawing.Point toolStrip18_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip18.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=682,Y=284}.
        /// </summary>
        public static System.Drawing.Point toolStrip19_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip19.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=682,Y=56}.
        /// </summary>
        public static System.Drawing.Point toolStrip2_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip2.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=730,Y=323}.
        /// </summary>
        public static System.Drawing.Point toolStrip20_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip20.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1042,Y=323}.
        /// </summary>
        public static System.Drawing.Point toolStrip21_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip21.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1154,Y=323}.
        /// </summary>
        public static System.Drawing.Point toolStrip22_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip22.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=541,Y=362}.
        /// </summary>
        public static System.Drawing.Point toolStrip23_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip23.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=995,Y=362}.
        /// </summary>
        public static System.Drawing.Point toolStrip24_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip24.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1107,Y=362}.
        /// </summary>
        public static System.Drawing.Point toolStrip25_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip25.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=401}.
        /// </summary>
        public static System.Drawing.Point toolStrip26_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip26.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=129,Y=401}.
        /// </summary>
        public static System.Drawing.Point toolStrip27_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip27.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=440}.
        /// </summary>
        public static System.Drawing.Point toolStrip28_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip28.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=129,Y=440}.
        /// </summary>
        public static System.Drawing.Point toolStrip29_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip29.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=199,Y=95}.
        /// </summary>
        public static System.Drawing.Point toolStrip3_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip3.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=591,Y=440}.
        /// </summary>
        public static System.Drawing.Point toolStrip30_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip30.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=503,Y=95}.
        /// </summary>
        public static System.Drawing.Point toolStrip4_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip4.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=771,Y=95}.
        /// </summary>
        public static System.Drawing.Point toolStrip5_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip5.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=538,Y=128}.
        /// </summary>
        public static System.Drawing.Point toolStrip6_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip6.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=823,Y=128}.
        /// </summary>
        public static System.Drawing.Point toolStrip7_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip7.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=403,Y=167}.
        /// </summary>
        public static System.Drawing.Point toolStrip8_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip8.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=225,Y=206}.
        /// </summary>
        public static System.Drawing.Point toolStrip9_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip9.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=498,Y=56}.
        /// </summary>
        public static System.Drawing.Point trackClassBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("trackClassBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddArtificialConstruction_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddArtificialConstruction.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddBallast_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddBallast.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddChamJoint_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddChamJoint.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddCheckSection_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddCheckSection.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddCommunication_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddCommunication.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddCoordinateGNSS_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddCoordinateGNSS.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddCurve_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddCurve.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddDeep_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddDeep.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddDefectsEarth_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddDefectsEarth.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddDimension_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddDimension.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddDistanceBetweenTracks_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddDistanceBetweenTracks.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddDistSections_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddDistSections.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddElCurve_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddElCurve.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddElevation_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddElevation.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddLongRails_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddLongRails.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddNonExistKm_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddNonExistKm.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddNonStandardKm_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddNonStandardKm.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddNormaWidth_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddNormaWidth.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddPdbSection_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddPdbSection.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddProfileObject_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddProfileObject.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddProfmarks_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddProfmarks.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddRailsBrace_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddRailsBrace.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddRailsSections_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddRailsSections.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddRefPoint_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddRefPoint.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddRepairProject_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddRepairProject.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddRfid_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddRfid.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddSpeed_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddSpeed.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddStationSection_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddStationSection.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddStCurve_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddStCurve.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddStraighteningThread_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddStraighteningThread.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddSwitch_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddSwitch.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddTempSpeed_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddTempSpeed.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddTrackClass_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddTrackClass.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddTraffic_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddTraffic.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddTsCrossTie_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddTsCrossTie.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbAddWaycat_Image {
            get {
                object obj = ResourceManager.GetObject("tsbAddWaycat.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbDeleteChamJoint_Image {
            get {
                object obj = ResourceManager.GetObject("tsbDeleteChamJoint.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbDeleteCheckSection_Image {
            get {
                object obj = ResourceManager.GetObject("tsbDeleteCheckSection.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbDeleteDimension_Image {
            get {
                object obj = ResourceManager.GetObject("tsbDeleteDimension.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbDeleteProfmarks_Image {
            get {
                object obj = ResourceManager.GetObject("tsbDeleteProfmarks.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbDeleteRefPoint_Image {
            get {
                object obj = ResourceManager.GetObject("tsbDeleteRefPoint.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbDeleteRepairProject_Image {
            get {
                object obj = ResourceManager.GetObject("tsbDeleteRepairProject.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbDeleteRfid_Image {
            get {
                object obj = ResourceManager.GetObject("tsbDeleteRfid.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbDeleteTraffic_Image {
            get {
                object obj = ResourceManager.GetObject("tsbDeleteTraffic.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbDeleteWaycat_Image {
            get {
                object obj = ResourceManager.GetObject("tsbDeleteWaycat.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveArtificialConstruction_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveArtificialConstruction.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveBallast_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveBallast.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveCommunication_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveCommunication.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveCoordinateGnss_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveCoordinateGnss.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveCurve_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveCurve.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveDeep_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveDeep.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveDefectsEarth_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveDefectsEarth.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveDistanceBetweenTracks_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveDistanceBetweenTracks.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveDistSection_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveDistSection.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveElCurve_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveElCurve.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveElevation_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveElevation.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveLongRails_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveLongRails.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveNonExistKm_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveNonExistKm.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveNonStandardKm_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveNonStandardKm.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveNormaWidth_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveNormaWidth.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemovePdbSections_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemovePdbSections.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveProfileObject_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveProfileObject.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveRailsBrace_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveRailsBrace.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveRailsSections_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveRailsSections.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveSpeed_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveSpeed.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveStationSection_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveStationSection.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveStCurve_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveStCurve.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveStraighteningThread_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveStraighteningThread.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveSwitch_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveSwitch.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveTempSpeed_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveTempSpeed.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveTrackClass_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveTrackClass.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tsbRemoveTsCrossTie_Image {
            get {
                object obj = ResourceManager.GetObject("tsbRemoveTsCrossTie.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=552,Y=17}.
        /// </summary>
        public static System.Drawing.Point tsCrossTie_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tsCrossTie.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=218,Y=128}.
        /// </summary>
        public static System.Drawing.Point tsNonExistKm_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tsNonExistKm.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=56}.
        /// </summary>
        public static System.Drawing.Point tsNonstandartKm_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tsNonstandartKm.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=234,Y=128}.
        /// </summary>
        public static System.Drawing.Point tsProfileObject_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tsProfileObject.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=256,Y=17}.
        /// </summary>
        public static System.Drawing.Point tsSections_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tsSections.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=381,Y=56}.
        /// </summary>
        public static System.Drawing.Point tsTrackClass_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tsTrackClass.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=389,Y=323}.
        /// </summary>
        public static System.Drawing.Point waycatBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("waycatBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
